let count = 0;
console.log("working..", count++);
console.log("working..", count++);
console.log("working..", count++);
console.log("working..", count++);
console.log("working..", count++);
console.log("working..", count++);
console.log("working..", count++);
console.log("working..", count++);
console.log("working..", count++);
console.log("working..", count++);
console.log("working..", count++);
console.log("working..", count++);
console.log("working..", count++);
console.logs("Not working..");